## STEP 1-A. Configuration

### make a function to check the library installed
### if yes, it load the libraries.
### if no, stop the script.
source("https://raw.githubusercontent.com/airbj31/04ExpDataAnalysis/master/week1/LoadLIB.R")

## set locale for non-english langaage user.
## this is required to print weekdays in English.
## only valid for windows user.
Sys.setlocale("LC_ALL","English")

## define the libraries we need

lib<-c("tidyr","dplyr","lubridate")

## load libraries or stop the script
## please ignore some noises generated by the LoadLIB()
## if the script stopped and show error messages, please install the required libraries before runing whole codes.

LoadLIB(lib)

## declaration of variables for downloading data
fileURL<-"https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"

## declaration of directory which downloaded contents stored.
dir<-"data"

### downloaded zip file name
dfile<-"EPC.zip"

## 0-C. dir check
if(!file.exists(dir)) {
  dir.create(dir)
}

## 0-D. download and unzip data

### make dest file path and name
dfile2<-paste(dir,dfile,sep="/")


## Download and unzip of the file
download.file(fileURL,destfile=dfile2)
unzip(dfile2,exdir=dir)

## Read Data
data<-read.table("./data/household_power_consumption.txt",sep=";",header=T,nrows=2075259,na.strings = "?")

## Filter the date following the assignment instruction.
## merge date and time in POSIxt POSIct form into DateTime variable by mutate
## deselect Date and Time variable since we do not need them anymore.

tdf <- filter(data,Date=="1/2/2007" | Date=="2/2/2007") %>% 
  mutate(DateTime=dmy(Date)+hms(Time)) %>% 
  select(-Date,-Time)

source("https://raw.githubusercontent.com/airbj31/04ExpDataAnalysis/master/week1/plot1.R")
source("https://raw.githubusercontent.com/airbj31/04ExpDataAnalysis/master/week1/plot2.R")
source("https://raw.githubusercontent.com/airbj31/04ExpDataAnalysis/master/week1/plot3.R")
source("https://raw.githubusercontent.com/airbj31/04ExpDataAnalysis/master/week1/plot4.R")
